In [2]:
import pandas as pd

# Tire Value

In [4]:
value = pd.read_csv('./Tire/raw_data/tire_product_Value_PCR_TBR_SP.csv')
value

,country,date,PRODUCT,INDICATORS,partner,value,year,month,HS Code,Category,General_Category
0,Spain,2022-01-01,"New pneumatic tyres, of rubber",VALUE_IN_EUROS,Andorra,2654.0,2022.0,1.0,4011,All,All
1,Spain,2022-02-01,"New pneumatic tyres, of rubber",VALUE_IN_EUROS,Andorra,364.0,2022.0,2.0,4011,All,All
2,Spain,2022-03-01,"New pneumatic tyres, of rubber",VALUE_IN_EUROS,Andorra,3602.0,2022.0,3.0,4011,All,All
3,Spain,2022-04-01,"New pneumatic tyres, of rubber",VALUE_IN_EUROS,Andorra,44.0,2022.0,4.0,4011,All,All
4,Spain,2022-05-01,"New pneumatic tyres, of rubber",VALUE_IN_EUROS,Andorra,1363.0,2022.0,5.0,4011,All,All
...,...,...,...,...,...,...,...,...,...,...,...
1158992,United Kingdom,2000-07-01,"New pneumatic tyres, of rubber, of a kind used...",VALUE_IN_EUROS,Zimbabwe,19411.0,2000.0,7.0,401110,PCR,PCR
1158993,United Kingdom,2001-07-01,"New pneumatic tyres, of rubber",VALUE_IN_EUROS,Zimbabwe,25011.0,2001.0,7.0,4011,All,All
1158994,United Kingdom,2001-12-01,"New pneumatic tyres, of rubber",VALUE_IN_EUROS,Zimbabwe,27822.0,2001.0,12.0,4011,All,All
1158995,United Kingdom,2001-07-01,"New pneumatic tyres, of rubber, of a kind used...",VALUE_IN_EUROS,Zimbabwe,25011.0,2001.0,7.0,401110,PCR,PCR
1158996,United Kingdom,2001-12-01,"New pneumatic tyres, of rubber, of a kind used...",VALUE_IN_EUROS,Zimbabwe,27822.0,2001.0,12.0,401110,PCR,PCR

In [5]:
value.columns

Index(['country', 'date', 'PRODUCT', 'INDICATORS', 'partner', 'value', 'year',
       'month', 'HS Code', 'Category', 'General_Category'],
      dtype='object')

In [6]:
value_product = value.groupby(['country', 'date', 'PRODUCT', 'partner', 'HS Code', 'Category', 'General_Category'])['value'].sum().reset_index()

In [7]:
value_product

,country,date,PRODUCT,partner,HS Code,Category,General_Category,value
0,Austria,2000-01-01,"New pneumatic tyres, of rubber",Argentina,4011,All,All,1247.0
1,Austria,2000-01-01,"New pneumatic tyres, of rubber",Belgium,4011,All,All,1331987.0
2,Austria,2000-01-01,"New pneumatic tyres, of rubber",Brazil,4011,All,All,26156.0
3,Austria,2000-01-01,"New pneumatic tyres, of rubber",China,4011,All,All,64678.0
4,Austria,2000-01-01,"New pneumatic tyres, of rubber",Czechia,4011,All,All,1111351.0
...,...,...,...,...,...,...,...,...
1158992,United Kingdom,2019-12-01,"Pneumatic tyres, new, of rubber, of a kind use...",Sri Lanka,40112090,TBR,TBR,6817.0
1158993,United Kingdom,2019-12-01,"Pneumatic tyres, new, of rubber, of a kind use...",Thailand,40112090,TBR,TBR,1507028.0
1158994,United Kingdom,2019-12-01,"Pneumatic tyres, new, of rubber, of a kind use...",Türkiye,40112090,TBR,TBR,587766.0
1158995,United Kingdom,2019-12-01,"Pneumatic tyres, new, of rubber, of a kind use...",United States,40112090,TBR,TBR,3613.0
1158996,United Kingdom,2019-12-01,"Pneumatic tyres, new, of rubber, of a kind use...",Viet Nam,40112090,TBR,TBR,591740.0

# Tire Weight

In [9]:
weight = pd.read_csv('./Tire/raw_data/tire_product_Weight_PCR_TBR_SP.csv')
weight

,country,date,PRODUCT,INDICATORS,partner,weight,year,month,HS Code,Category,General_Category
0,Spain,2022-01-01,"New pneumatic tyres, of rubber",QUANTITY_IN_100KG,Andorra,460.0,2022.0,1.0,4011,All,All
1,Spain,2022-02-01,"New pneumatic tyres, of rubber",QUANTITY_IN_100KG,Andorra,48.0,2022.0,2.0,4011,All,All
2,Spain,2022-03-01,"New pneumatic tyres, of rubber",QUANTITY_IN_100KG,Andorra,300.0,2022.0,3.0,4011,All,All
3,Spain,2022-04-01,"New pneumatic tyres, of rubber",QUANTITY_IN_100KG,Andorra,5.0,2022.0,4.0,4011,All,All
4,Spain,2022-05-01,"New pneumatic tyres, of rubber",QUANTITY_IN_100KG,Andorra,96.0,2022.0,5.0,4011,All,All
...,...,...,...,...,...,...,...,...,...,...,...
1158992,United Kingdom,2000-07-01,"New pneumatic tyres, of rubber, of a kind used...",QUANTITY_IN_100KG,Zimbabwe,4800.0,2000.0,7.0,401110,PCR,PCR
1158993,United Kingdom,2001-07-01,"New pneumatic tyres, of rubber",QUANTITY_IN_100KG,Zimbabwe,4400.0,2001.0,7.0,4011,All,All
1158994,United Kingdom,2001-12-01,"New pneumatic tyres, of rubber",QUANTITY_IN_100KG,Zimbabwe,5000.0,2001.0,12.0,4011,All,All
1158995,United Kingdom,2001-07-01,"New pneumatic tyres, of rubber, of a kind used...",QUANTITY_IN_100KG,Zimbabwe,4400.0,2001.0,7.0,401110,PCR,PCR
1158996,United Kingdom,2001-12-01,"New pneumatic tyres, of rubber, of a kind used...",QUANTITY_IN_100KG,Zimbabwe,5000.0,2001.0,12.0,401110,PCR,PCR

In [10]:
weight_product = weight.groupby(['country', 'date', 'PRODUCT', 'partner', 'HS Code', 'Category', 'General_Category'])['weight'].sum().reset_index()

In [11]:
weight_product

,country,date,PRODUCT,partner,HS Code,Category,General_Category,weight
0,Austria,2000-01-01,"New pneumatic tyres, of rubber",Argentina,4011,All,All,300.0
1,Austria,2000-01-01,"New pneumatic tyres, of rubber",Belgium,4011,All,All,531700.0
2,Austria,2000-01-01,"New pneumatic tyres, of rubber",Brazil,4011,All,All,6300.0
3,Austria,2000-01-01,"New pneumatic tyres, of rubber",China,4011,All,All,10600.0
4,Austria,2000-01-01,"New pneumatic tyres, of rubber",Czechia,4011,All,All,430700.0
...,...,...,...,...,...,...,...,...
1158992,United Kingdom,2019-12-01,"Pneumatic tyres, new, of rubber, of a kind use...",Sri Lanka,40112090,TBR,TBR,2450.0
1158993,United Kingdom,2019-12-01,"Pneumatic tyres, new, of rubber, of a kind use...",Thailand,40112090,TBR,TBR,646026.0
1158994,United Kingdom,2019-12-01,"Pneumatic tyres, new, of rubber, of a kind use...",Türkiye,40112090,TBR,TBR,172134.0
1158995,United Kingdom,2019-12-01,"Pneumatic tyres, new, of rubber, of a kind use...",United States,40112090,TBR,TBR,423.0
1158996,United Kingdom,2019-12-01,"Pneumatic tyres, new, of rubber, of a kind use...",Viet Nam,40112090,TBR,TBR,248526.0

# merge

In [13]:
eurostat = value_product.merge(weight_product,on = ['country', 'date', 'PRODUCT', 'partner', 'HS Code', 'Category', 'General_Category'] ,how='inner')

In [14]:
eurostat['weight'] *=100

In [15]:
eurostat['Type'] = 'Tyre'

In [16]:
eurostat

,country,date,PRODUCT,partner,HS Code,Category,General_Category,value,weight,Type
0,Austria,2000-01-01,"New pneumatic tyres, of rubber",Argentina,4011,All,All,1247.0,30000.0,Tyre
1,Austria,2000-01-01,"New pneumatic tyres, of rubber",Belgium,4011,All,All,1331987.0,53170000.0,Tyre
2,Austria,2000-01-01,"New pneumatic tyres, of rubber",Brazil,4011,All,All,26156.0,630000.0,Tyre
3,Austria,2000-01-01,"New pneumatic tyres, of rubber",China,4011,All,All,64678.0,1060000.0,Tyre
4,Austria,2000-01-01,"New pneumatic tyres, of rubber",Czechia,4011,All,All,1111351.0,43070000.0,Tyre
...,...,...,...,...,...,...,...,...,...,...
1158977,United Kingdom,2019-12-01,"Pneumatic tyres, new, of rubber, of a kind use...",Sri Lanka,40112090,TBR,TBR,6817.0,245000.0,Tyre
1158978,United Kingdom,2019-12-01,"Pneumatic tyres, new, of rubber, of a kind use...",Thailand,40112090,TBR,TBR,1507028.0,64602600.0,Tyre
1158979,United Kingdom,2019-12-01,"Pneumatic tyres, new, of rubber, of a kind use...",Türkiye,40112090,TBR,TBR,587766.0,17213400.0,Tyre
1158980,United Kingdom,2019-12-01,"Pneumatic tyres, new, of rubber, of a kind use...",United States,40112090,TBR,TBR,3613.0,42300.0,Tyre
1158981,United Kingdom,2019-12-01,"Pneumatic tyres, new, of rubber, of a kind use...",Viet Nam,40112090,TBR,TBR,591740.0,24852600.0,Tyre

In [17]:
eurostat.columns

Index(['country', 'date', 'PRODUCT', 'partner', 'HS Code', 'Category',
       'General_Category', 'value', 'weight', 'Type'],
      dtype='object')

In [18]:
eurostat_final = eurostat[['date', 'HS Code', 'PRODUCT', 'Category', 'General_Category', 'country', 'partner', 'value', 'weight', 'Type']]

In [19]:
category_list = ['PCR', 'TBR', 'Specialty']
eurostat_product =  eurostat_final[eurostat_final['General_Category'].isin(category_list)]

In [20]:
# eurostat_product = eurostat_product[(eurostat_product['date']<"2025-10-01")]
eurostat_product

,date,HS Code,PRODUCT,Category,General_Category,country,partner,value,weight,Type
47,2000-01-01,401110,"New pneumatic tyres, of rubber, of a kind used...",PCR,PCR,Austria,Argentina,1247.0,30000.0,Tyre
48,2000-01-01,401110,"New pneumatic tyres, of rubber, of a kind used...",PCR,PCR,Austria,Belgium,633627.0,22420000.0,Tyre
49,2000-01-01,401110,"New pneumatic tyres, of rubber, of a kind used...",PCR,PCR,Austria,Brazil,26156.0,630000.0,Tyre
50,2000-01-01,401110,"New pneumatic tyres, of rubber, of a kind used...",PCR,PCR,Austria,Czechia,620364.0,23900000.0,Tyre
51,2000-01-01,401110,"New pneumatic tyres, of rubber, of a kind used...",PCR,PCR,Austria,Denmark,110.0,0.0,Tyre
...,...,...,...,...,...,...,...,...,...,...
1158977,2019-12-01,40112090,"Pneumatic tyres, new, of rubber, of a kind use...",TBR,TBR,United Kingdom,Sri Lanka,6817.0,245000.0,Tyre
1158978,2019-12-01,40112090,"Pneumatic tyres, new, of rubber, of a kind use...",TBR,TBR,United Kingdom,Thailand,1507028.0,64602600.0,Tyre
1158979,2019-12-01,40112090,"Pneumatic tyres, new, of rubber, of a kind use...",TBR,TBR,United Kingdom,Türkiye,587766.0,17213400.0,Tyre
1158980,2019-12-01,40112090,"Pneumatic tyres, new, of rubber, of a kind use...",TBR,TBR,United Kingdom,United States,3613.0,42300.0,Tyre
1158981,2019-12-01,40112090,"Pneumatic tyres, new, of rubber, of a kind use...",TBR,TBR,United Kingdom,Viet Nam,591740.0,24852600.0,Tyre

# Vehicle Value

In [22]:
vehicle_value = pd.read_csv('./Vehicle/Data/vehicle_product_value.csv')
vehicle_value

,country,date,PRODUCT,INDICATORS,partner,value,year,month,HS Code,General_Category
0,Germany,2022-05-01,Tractors (other than tractors of heading 8709),VALUE_IN_EUROS,Andorra,14600.0,2022.0,5.0,8701,Specialty
1,Germany,2022-11-01,Tractors (other than tractors of heading 8709),VALUE_IN_EUROS,Andorra,44200.0,2022.0,11.0,8701,Specialty
2,Spain,2022-09-01,Tractors (other than tractors of heading 8709),VALUE_IN_EUROS,Andorra,13000.0,2022.0,9.0,8701,Specialty
3,Spain,2022-10-01,Tractors (other than tractors of heading 8709),VALUE_IN_EUROS,Andorra,102422.0,2022.0,10.0,8701,Specialty
4,France,2022-05-01,Tractors (other than tractors of heading 8709),VALUE_IN_EUROS,Andorra,40005.0,2022.0,5.0,8701,Specialty
...,...,...,...,...,...,...,...,...,...,...
443649,Netherlands,2017-10-01,"Motor vehicles for the transport of goods, inc...",VALUE_IN_EUROS,Zimbabwe,12500.0,2017.0,10.0,8704,TBR
443650,France,2017-01-01,Special purpose motor vehicles (other than tho...,VALUE_IN_EUROS,Zimbabwe,414200.0,2017.0,1.0,8705,Specialty
443651,Belgium,2021-04-01,Motor cars and other motor vehicles principall...,VALUE_IN_EUROS,Zimbabwe,95311.0,2021.0,4.0,8703,PCR
443652,Belgium,2021-08-01,Motor cars and other motor vehicles principall...,VALUE_IN_EUROS,Zimbabwe,95311.0,2021.0,8.0,8703,PCR
443653,Belgium,2021-12-01,Motor cars and other motor vehicles principall...,VALUE_IN_EUROS,Zimbabwe,7767.0,2021.0,12.0,8703,PCR

In [23]:
vehicle_value.columns

Index(['country', 'date', 'PRODUCT', 'INDICATORS', 'partner', 'value', 'year',
       'month', 'HS Code', 'General_Category'],
      dtype='object')

In [24]:
vehicle_value_product = vehicle_value.groupby(['country', 'date', 'PRODUCT', 'partner', 'HS Code','General_Category'])['value'].sum().reset_index()
vehicle_value_product

,country,date,PRODUCT,partner,HS Code,General_Category,value
0,Austria,2017-01-01,Electrical vehicles not fitted with lifting or...,China,870911,Specialty,1460.0
1,Austria,2017-01-01,Electrical vehicles not fitted with lifting or...,France,870911,Specialty,18371.0
2,Austria,2017-01-01,Electrical vehicles not fitted with lifting or...,Germany,870911,Specialty,758762.0
3,Austria,2017-01-01,Electrical vehicles not fitted with lifting or...,Italy,870911,Specialty,6977.0
4,Austria,2017-01-01,Motor cars and other motor vehicles principall...,Belgium,8703,PCR,27238413.0
...,...,...,...,...,...,...,...
443649,United Kingdom,2019-12-01,"Trailers and semi-trailers, not designed for r...",Türkiye,871640,TBR,37311.0
443650,United Kingdom,2019-12-01,"Trailers and semi-trailers, not designed for r...",United States,871640,TBR,563487.0
443651,United Kingdom,2019-12-01,"Works trucks, self-propelled, not fitted with ...",China,870919,Specialty,22180.0
443652,United Kingdom,2019-12-01,"Works trucks, self-propelled, not fitted with ...",Netherlands,870919,Specialty,366207.0
443653,United Kingdom,2019-12-01,"Works trucks, self-propelled, not fitted with ...",United States,870919,Specialty,84061.0

# Vehicle Weight

In [26]:
vehicle_weight = pd.read_csv('./Vehicle/Data/vehicle_product_weight.csv')
vehicle_weight

,country,date,PRODUCT,INDICATORS,partner,weight,year,month,HS Code,General_Category
0,Germany,2022-05-01,Tractors (other than tractors of heading 8709),QUANTITY_IN_100KG,Andorra,260.00,2022.0,5.0,8701,Specialty
1,Germany,2022-11-01,Tractors (other than tractors of heading 8709),QUANTITY_IN_100KG,Andorra,130.30,2022.0,11.0,8701,Specialty
2,Spain,2022-09-01,Tractors (other than tractors of heading 8709),QUANTITY_IN_100KG,Andorra,85.30,2022.0,9.0,8701,Specialty
3,Spain,2022-10-01,Tractors (other than tractors of heading 8709),QUANTITY_IN_100KG,Andorra,75.64,2022.0,10.0,8701,Specialty
4,France,2022-05-01,Tractors (other than tractors of heading 8709),QUANTITY_IN_100KG,Andorra,131.90,2022.0,5.0,8701,Specialty
...,...,...,...,...,...,...,...,...,...,...
443649,Netherlands,2017-10-01,"Motor vehicles for the transport of goods, inc...",QUANTITY_IN_100KG,Zimbabwe,76.50,2017.0,10.0,8704,TBR
443650,France,2017-01-01,Special purpose motor vehicles (other than tho...,QUANTITY_IN_100KG,Zimbabwe,170.00,2017.0,1.0,8705,Specialty
443651,Belgium,2021-04-01,Motor cars and other motor vehicles principall...,QUANTITY_IN_100KG,Zimbabwe,45.40,2021.0,4.0,8703,PCR
443652,Belgium,2021-08-01,Motor cars and other motor vehicles principall...,QUANTITY_IN_100KG,Zimbabwe,18.20,2021.0,8.0,8703,PCR
443653,Belgium,2021-12-01,Motor cars and other motor vehicles principall...,QUANTITY_IN_100KG,Zimbabwe,22.01,2021.0,12.0,8703,PCR

In [27]:
vehicle_weight_product = vehicle_weight.groupby(['country', 'date', 'PRODUCT', 'partner', 'HS Code','General_Category'])['weight'].sum().reset_index()
vehicle_weight_product

,country,date,PRODUCT,partner,HS Code,General_Category,weight
0,Austria,2017-01-01,Electrical vehicles not fitted with lifting or...,China,870911,Specialty,3.37
1,Austria,2017-01-01,Electrical vehicles not fitted with lifting or...,France,870911,Specialty,14.00
2,Austria,2017-01-01,Electrical vehicles not fitted with lifting or...,Germany,870911,Specialty,387.30
3,Austria,2017-01-01,Electrical vehicles not fitted with lifting or...,Italy,870911,Specialty,8.48
4,Austria,2017-01-01,Motor cars and other motor vehicles principall...,Belgium,8703,PCR,22660.58
...,...,...,...,...,...,...,...
443649,United Kingdom,2019-12-01,"Trailers and semi-trailers, not designed for r...",Türkiye,871640,TBR,83.00
443650,United Kingdom,2019-12-01,"Trailers and semi-trailers, not designed for r...",United States,871640,TBR,720.99
443651,United Kingdom,2019-12-01,"Works trucks, self-propelled, not fitted with ...",China,870919,Specialty,17.18
443652,United Kingdom,2019-12-01,"Works trucks, self-propelled, not fitted with ...",Netherlands,870919,Specialty,381.95
443653,United Kingdom,2019-12-01,"Works trucks, self-propelled, not fitted with ...",United States,870919,Specialty,35.41

# Merge

In [29]:
eurostat_vehicle = vehicle_value_product.merge(vehicle_weight_product,on = ['country', 'date', 'PRODUCT', 'partner', 'HS Code', 'General_Category'] ,how='inner')

In [30]:
eurostat_vehicle['weight'] *=100

In [31]:
eurostat_vehicle['Type'] = 'Vehicle'

In [32]:
eurostat_vehicle

,country,date,PRODUCT,partner,HS Code,General_Category,value,weight,Type
0,Austria,2017-01-01,Electrical vehicles not fitted with lifting or...,China,870911,Specialty,1460.0,337.0,Vehicle
1,Austria,2017-01-01,Electrical vehicles not fitted with lifting or...,France,870911,Specialty,18371.0,1400.0,Vehicle
2,Austria,2017-01-01,Electrical vehicles not fitted with lifting or...,Germany,870911,Specialty,758762.0,38730.0,Vehicle
3,Austria,2017-01-01,Electrical vehicles not fitted with lifting or...,Italy,870911,Specialty,6977.0,848.0,Vehicle
4,Austria,2017-01-01,Motor cars and other motor vehicles principall...,Belgium,8703,PCR,27238413.0,2266058.0,Vehicle
...,...,...,...,...,...,...,...,...,...
443649,United Kingdom,2019-12-01,"Trailers and semi-trailers, not designed for r...",Türkiye,871640,TBR,37311.0,8300.0,Vehicle
443650,United Kingdom,2019-12-01,"Trailers and semi-trailers, not designed for r...",United States,871640,TBR,563487.0,72099.0,Vehicle
443651,United Kingdom,2019-12-01,"Works trucks, self-propelled, not fitted with ...",China,870919,Specialty,22180.0,1718.0,Vehicle
443652,United Kingdom,2019-12-01,"Works trucks, self-propelled, not fitted with ...",Netherlands,870919,Specialty,366207.0,38195.0,Vehicle
443653,United Kingdom,2019-12-01,"Works trucks, self-propelled, not fitted with ...",United States,870919,Specialty,84061.0,3541.0,Vehicle

# concate

In [34]:
eurostat_tyre_vehicle = pd.concat([eurostat_product,eurostat_vehicle])

In [35]:
eurostat_tyre_vehicle

,date,HS Code,PRODUCT,Category,General_Category,country,partner,value,weight,Type
47,2000-01-01,401110,"New pneumatic tyres, of rubber, of a kind used...",PCR,PCR,Austria,Argentina,1247.0,30000.0,Tyre
48,2000-01-01,401110,"New pneumatic tyres, of rubber, of a kind used...",PCR,PCR,Austria,Belgium,633627.0,22420000.0,Tyre
49,2000-01-01,401110,"New pneumatic tyres, of rubber, of a kind used...",PCR,PCR,Austria,Brazil,26156.0,630000.0,Tyre
50,2000-01-01,401110,"New pneumatic tyres, of rubber, of a kind used...",PCR,PCR,Austria,Czechia,620364.0,23900000.0,Tyre
51,2000-01-01,401110,"New pneumatic tyres, of rubber, of a kind used...",PCR,PCR,Austria,Denmark,110.0,0.0,Tyre
...,...,...,...,...,...,...,...,...,...,...
443649,2019-12-01,871640,"Trailers and semi-trailers, not designed for r...",NaN,TBR,United Kingdom,Türkiye,37311.0,8300.0,Vehicle
443650,2019-12-01,871640,"Trailers and semi-trailers, not designed for r...",NaN,TBR,United Kingdom,United States,563487.0,72099.0,Vehicle
443651,2019-12-01,870919,"Works trucks, self-propelled, not fitted with ...",NaN,Specialty,United Kingdom,China,22180.0,1718.0,Vehicle
443652,2019-12-01,870919,"Works trucks, self-propelled, not fitted with ...",NaN,Specialty,United Kingdom,Netherlands,366207.0,38195.0,Vehicle
443653,2019-12-01,870919,"Works trucks, self-propelled, not fitted with ...",NaN,Specialty,United Kingdom,United States,84061.0,3541.0,Vehicle

In [36]:
print(eurostat_tyre_vehicle['partner'].unique())

['Argentina' 'Belgium' 'Brazil' 'Czechia' 'Denmark' 'Finland' 'France'
 'Germany' 'Hungary' 'Indonesia' 'Italy' 'Japan' 'Korea, Republic of'
 'Luxembourg' 'Morocco' 'Netherlands' 'Philippines' 'Poland' 'Slovenia'
 'Spain' 'Sweden' 'Switzerland' 'Türkiye' 'United Kingdom' 'United States'
 'Israel' 'Slovakia' 'China' 'Thailand' 'Bosnia and Herzegovina' 'Romania'
 'Venezuela, Bolivarian Republic of' 'Norway' 'Liechtenstein' 'Singapore'
 'Yugoslavia' 'South Africa' 'Australia' 'Croatia' 'Portugal' 'India'
 'Egypt' 'Taiwan' 'Greece' 'United Arab Emirates' 'Canada' 'Ireland'
 'Russian Federation' 'Ukraine' 'Tuvalu' 'Chile' 'Mexico'
 'Serbia and Montenegro' 'Malaysia' 'Estonia'
 'Virgin Islands, United States' 'Serbia' 'Lithuania' 'Bulgaria'
 'North Macedonia' 'Latvia' 'New Zealand' 'Malta' 'Bahrain' 'Montenegro'
 'Viet Nam' 'Belarus' 'Kosovo' 'Sri Lanka' 'Oman' 'Hong Kong'
 'Saudi Arabia' 'Azerbaijan' 'Iceland' 'Cambodia' 'Qatar' 'Austria'
 'Iran, Islamic Republic of' 'Cameroon' 'Uruguay' 'Andorra' 'Armenia'
 'Pitcairn' 'Jordan' 'Netherlands Antilles' 'Kuwait' 'Pakistan' 'Nigeria'
 'Ecuador' 'Lebanon' 'Côte d’Ivoire' 'Algeria' 'Syrian Arab Republic'
 'Cyprus' 'Mongolia' 'Dominica' 'Falkland Islands' 'El Salvador'
 'Congo, Democratic Republic of' 'Virgin Islands, British' 'Jamaica'
 'Costa Rica' 'Panama' 'Georgia' 'New Caledonia' 'Dominican Republic'
 'Libya' 'Belize' 'Ghana' 'Cuba' 'Colombia' 'Kazakhstan' 'Guyana'
 'Liberia' 'Sierra Leone' 'Angola' 'Yemen' 'Honduras' 'Tunisia'
 'Afghanistan' 'Ethiopia' 'Lesotho'
 'Korea, Democratic People’s Republic of' 'Moldova, Republic of' 'Nauru'
 'Kyrgyzstan' 'San Marino' 'Gibraltar' 'Albania' 'Gambia' 'Barbados'
 'Zambia' 'Zimbabwe' 'Tajikistan' 'Turkmenistan'
 'Tanzania, United Republic of' 'Central African Republic' 'Haiti'
 'Bangladesh' 'Mali' 'Sudan' 'Cabo Verde' 'New Zealand Oceania' 'Macao'
 'Uzbekistan' 'Mauritius' 'Greenland' 'Faroe Islands' 'Bahamas' 'Niger'
 'Suriname' 'Timor-Leste' 'Brunei Darussalam' 'Benin' 'Montenegro.1'
 'Madagascar' 'French Polynesia' 'Mayotte' 'Trinidad and Tobago'
 'Sint Maarten' 'Paraguay' 'Senegal' 'Saint Barthélemy' 'Papua New Guinea'
 'Togo' 'United States Minor Outlying Islands' 'Chad' 'Kenya' 'St Lucia'
 'Peru' 'Guinea' 'Somalia' 'Djibouti' 'Grenada' 'Mauritania' 'Eritrea'
 'Namibia' 'Cook Islands' 'Gabon' 'Curaçao' 'Iraq' 'Uganda'
 'Lao People’s Democratic Republic' 'Montserrat' 'Sao Tome and Principe'
 'Antigua and Barbuda' 'Marshall Islands' 'Christmas Island' 'Burundi'
 'Ceuta' 'Botswana' 'St Pierre and Miquelon' 'Rwanda' 'Tonga'
 'Occupied Palestinian Territory' 'Seychelles' 'American Samoa'
 'Guatemala' 'Tokelau' 'Northern Mariana Islands'
 'Turks and Caicos Islands' 'Nicaragua'
 'Saint Helena, Ascension and Tristan da Cunha' 'Bhutan' 'Mozambique'
 'Cocos Islands' 'Samoa' 'Congo' 'East Timor' 'Bermuda' 'Myanmar'
 'Burkina Faso' 'Melilla' 'Equatorial Guinea' 'Solomon Islands'
 'Cayman Islands' 'Bolivia, Plurinational State of' 'Vanuatu'
 'Guinea-Bissau' 'South Georgia and South Sandwich Islands'
 'Wallis and Futuna' 'Aruba' 'Malawi' 'South Sudan' 'Fiji'
 'Bonaire, Sint Eustatius and Saba' 'French Southern Territories' 'Nepal'
 'British Indian Ocean Territory' 'Eswatini' 'Holy See' 'Comoros'
 'St Vincent and the Grenadines' 'Antarctica' 'High seas' 'Kiribati'
 'Bouvet Island' 'Guam' 'St Kitts and Nevis']

In [37]:
continent_map = {
    # Europe
    'Belgium': 'Europe', 'Czechia': 'Europe', 'Denmark': 'Europe', 'Finland': 'Europe', 'France': 'Europe',
    'Germany': 'Europe', 'Hungary': 'Europe', 'Italy': 'Europe', 'Luxembourg': 'Europe', 'Netherlands': 'Europe',
    'Poland': 'Europe', 'Slovenia': 'Europe', 'Spain': 'Europe', 'Sweden': 'Europe', 'Switzerland': 'Europe',
    'United Kingdom': 'Europe', 'Slovakia': 'Europe', 'Bosnia and Herzegovina': 'Europe', 'Romania': 'Europe',
    'Norway': 'Europe', 'Liechtenstein': 'Europe', 'Croatia': 'Europe', 'Portugal': 'Europe', 'Greece': 'Europe',
    'Ireland': 'Europe', 'Estonia': 'Europe', 'Serbia': 'Europe', 'Lithuania': 'Europe', 'Bulgaria': 'Europe',
    'North Macedonia': 'Europe', 'Latvia': 'Europe', 'Malta': 'Europe', 'Montenegro': 'Europe', 'Austria': 'Europe',
    'Andorra': 'Europe', 'San Marino': 'Europe', 'Gibraltar': 'Europe', 'Albania': 'Europe', 'Iceland': 'Europe',
    'Cyprus': 'Europe', 'Belarus': 'Europe', 'Ukraine': 'Europe', 'Russian Federation': 'Europe',
    'Moldova, Republic of': 'Europe', 'Kosovo': 'Europe', 'Faroe Islands': 'Europe',
    'Yugoslavia': 'Europe', 'Serbia and Montenegro': 'Europe', 'Montenegro.1': 'Europe', 'Armenia': 'Europe',
    'Holy See': 'Europe',

    # Asia
    'Indonesia': 'Asia', 'Japan': 'Asia', 'Korea, Republic of': 'Asia', 'Philippines': 'Asia', 'Türkiye': 'Asia',
    'Israel': 'Asia', 'China': 'Asia', 'Thailand': 'Asia', 'India': 'Asia', 'Taiwan': 'Asia', 'Singapore': 'Asia',
    'Viet Nam': 'Asia', 'Sri Lanka': 'Asia', 'Oman': 'Asia', 'Hong Kong': 'Asia', 'Saudi Arabia': 'Asia',
    'Azerbaijan': 'Asia', 'Cambodia': 'Asia', 'Qatar': 'Asia', 'Iran, Islamic Republic of': 'Asia',
    'Jordan': 'Asia', 'Kuwait': 'Asia', 'Pakistan': 'Asia', 'Lebanon': 'Asia', 'Syrian Arab Republic': 'Asia',
    'Mongolia': 'Asia', 'Georgia': 'Asia', 'Kazakhstan': 'Asia', 'Kyrgyzstan': 'Asia', 'Tajikistan': 'Asia',
    'Turkmenistan': 'Asia', 'Uzbekistan': 'Asia', 'Afghanistan': 'Asia', 'Bangladesh': 'Asia', 'Macao': 'Asia',
    'Brunei Darussalam': 'Asia', 'Malaysia': 'Asia', 'Myanmar': 'Asia', 'Lao People’s Democratic Republic': 'Asia',
    'Timor-Leste': 'Asia', 'East Timor': 'Asia', 'Bhutan': 'Asia', 'Bahrain': 'Asia', 'Yemen': 'Asia', 'Iraq': 'Asia',
    'Korea, Democratic People’s Republic of': 'Asia', 'Occupied Palestinian Territory': 'Asia',
    'United Arab Emirates': 'Asia',
    'Nepal': 'Asia',

    # Africa
    'Morocco': 'Africa', 'South Africa': 'Africa', 'Egypt': 'Africa', 'Nigeria': 'Africa', 'Côte d’Ivoire': 'Africa',
    'Algeria': 'Africa', 'Cameroon': 'Africa', 'Libya': 'Africa', 'Ghana': 'Africa', 'Angola': 'Africa',
    'Ethiopia': 'Africa', 'Lesotho': 'Africa', 'Tunisia': 'Africa', 'Congo, Democratic Republic of': 'Africa',
    'Congo': 'Africa', 'Zambia': 'Africa', 'Zimbabwe': 'Africa', 'Tanzania, United Republic of': 'Africa',
    'Central African Republic': 'Africa', 'Mali': 'Africa', 'Sudan': 'Africa', 'Cabo Verde': 'Africa',
    'Madagascar': 'Africa', 'Mauritius': 'Africa', 'Benin': 'Africa', 'Senegal': 'Africa', 'Togo': 'Africa',
    'Chad': 'Africa', 'Kenya': 'Africa', 'Guinea': 'Africa', 'Somalia': 'Africa', 'Djibouti': 'Africa',
    'Mauritania': 'Africa', 'Eritrea': 'Africa', 'Namibia': 'Africa', 'Gabon': 'Africa', 'Uganda': 'Africa',
    'Burundi': 'Africa', 'Rwanda': 'Africa', 'Botswana': 'Africa', 'Mozambique': 'Africa', 'Burkina Faso': 'Africa',
    'Equatorial Guinea': 'Africa', 'Gambia': 'Africa', 'Sierra Leone': 'Africa', 'Liberia': 'Africa',
    'Sao Tome and Principe': 'Africa', 'Niger': 'Africa', 'Mayotte': 'Africa', 'Seychelles': 'Africa',
    'Ceuta': 'Africa', 'Melilla': 'Africa', 'Saint Helena, Ascension and Tristan da Cunha': 'Africa',
    'Guinea-Bissau': 'Africa', 'Malawi': 'Africa', 'South Sudan': 'Africa', 'British Indian Ocean Territory': 'Africa',
    'Eswatini': 'Africa', 'Comoros': 'Africa',

    # North America (包括中美洲和加勒比地区)
    'Canada': 'North America', 'United States': 'North America', 'Mexico': 'North America',
    'Greenland': 'North America', 'Bermuda': 'North America', 'St Pierre and Miquelon': 'North America',
    'Belize': 'North America', 'Costa Rica': 'North America', 'El Salvador': 'North America',
    'Guatemala': 'North America', 'Honduras': 'North America', 'Nicaragua': 'North America', 'Panama': 'North America',
    'Jamaica': 'North America', 'Cuba': 'North America', 'Haiti': 'North America', 'Dominican Republic': 'North America',
    'Bahamas': 'North America', 'Barbados': 'North America', 'Trinidad and Tobago': 'North America',
    'Dominica': 'North America', 'Antigua and Barbuda': 'North America', 'St Lucia': 'North America',
    'Grenada': 'North America', 'Virgin Islands, United States': 'North America',
    'Virgin Islands, British': 'North America', 'Cayman Islands': 'North America',
    'Turks and Caicos Islands': 'North America', 'Montserrat': 'North America',
    'Saint Barthélemy': 'North America', 'Sint Maarten': 'North America', 'Curaçao': 'North America',
    'Netherlands Antilles': 'North America',
    'Aruba': 'North America', 'St Vincent and the Grenadines': 'North America',
    'Bonaire, Sint Eustatius and Saba': 'North America', 'St Kitts and Nevis': 'North America',

    # South America
    'Argentina': 'South America', 'Brazil': 'South America', 'Venezuela, Bolivarian Republic of': 'South America',
    'Chile': 'South America', 'Uruguay': 'South America', 'Paraguay': 'South America', 'Peru': 'South America',
    'Colombia': 'South America', 'Ecuador': 'South America', 'Bolivia, Plurinational State of': 'South America',
    'Guyana': 'South America', 'Suriname': 'South America', 'Falkland Islands': 'South America',
    'South Georgia and South Sandwich Islands': 'South America',

    # Oceania
    'Australia': 'Oceania', 'New Zealand': 'Oceania', 'Tuvalu': 'Oceania', 'Nauru': 'Oceania',
    'Papua New Guinea': 'Oceania', 'New Caledonia': 'Oceania', 'French Polynesia': 'Oceania',
    'Pitcairn': 'Oceania', 'Cook Islands': 'Oceania', 'Marshall Islands': 'Oceania', 'Tonga': 'Oceania',
    'American Samoa': 'Oceania', 'Tokelau': 'Oceania', 'Northern Mariana Islands': 'Oceania',
    'Samoa': 'Oceania', 'Solomon Islands': 'Oceania', 'Cocos Islands': 'Oceania',
    'Christmas Island': 'Oceania', 'New Zealand Oceania': 'Oceania',
    'United States Minor Outlying Islands': 'Oceania',
    'Wallis and Futuna': 'Oceania', 'Fiji': 'Oceania', 'Vanuatu': 'Oceania',
    'Kiribati': 'Oceania', 'Guam': 'Oceania',

    # Antarctica / Other
    'Antarctica': 'Antarctica', 'French Southern Territories': 'Antarctica', 'Bouvet Island': 'Antarctica',
    'High seas': 'Other',
}



eurostat_tyre_vehicle['partner_continent'] = eurostat_tyre_vehicle['partner'].map(continent_map).fillna('Unknown')
# 查看结果
print(eurostat_tyre_vehicle[['partner', 'partner_continent']].head(20))
print("\n大洲分布：")
print(eurostat_tyre_vehicle['partner_continent'].value_counts())
# 添加列，未匹配的填 'Unknown'

               partner partner_continent
47           Argentina     South America
48             Belgium            Europe
49              Brazil     South America
50             Czechia            Europe
51             Denmark            Europe
52             Finland            Europe
53              France            Europe
54             Germany            Europe
55             Hungary            Europe
56           Indonesia              Asia
57               Italy            Europe
58               Japan              Asia
59  Korea, Republic of              Asia
60          Luxembourg            Europe
61             Morocco            Africa
62         Netherlands            Europe
63         Philippines              Asia
64              Poland            Europe
65            Slovenia            Europe
66               Spain            Europe

大洲分布：
partner_continent
Europe           792561
Asia             222099
North America     41875
Africa            20832
South America     12101
Oceania            3795
Antarctica           16
Other                 3
Name: count, dtype: int64

In [38]:
eurostat_tyre_vehicle[eurostat_tyre_vehicle['partner_continent']=='Unknown']['partner'].unique()

array([], dtype=object)

In [39]:
# 细分子区域映射字典（基于联合国子区域，覆盖了列表中几乎所有国家）
region_map = {
    # 欧洲子区域
    'Denmark': 'Northern Europe', 'Finland': 'Northern Europe', 'Sweden': 'Northern Europe', 'Norway': 'Northern Europe',
    'Iceland': 'Northern Europe', 'Estonia': 'Northern Europe', 'Latvia': 'Northern Europe', 'Lithuania': 'Northern Europe',
    'United Kingdom': 'Northern Europe', 'Ireland': 'Northern Europe', 'Faroe Islands': 'Northern Europe',

    'Belgium': 'Western Europe', 'France': 'Western Europe', 'Germany': 'Western Europe', 'Luxembourg': 'Western Europe',
    'Netherlands': 'Western Europe', 'Switzerland': 'Western Europe', 'Liechtenstein': 'Western Europe', 'Austria': 'Western Europe',

    'Italy': 'Southern Europe', 'Spain': 'Southern Europe', 'Portugal': 'Southern Europe', 'Greece': 'Southern Europe',
    'Malta': 'Southern Europe', 'Croatia': 'Southern Europe', 'Slovenia': 'Southern Europe', 'Andorra': 'Southern Europe',
    'San Marino': 'Southern Europe', 'Gibraltar': 'Southern Europe', 'Albania': 'Southern Europe', 'Bosnia and Herzegovina': 'Southern Europe',
    'North Macedonia': 'Southern Europe', 'Montenegro': 'Southern Europe', 'Serbia': 'Southern Europe', 'Kosovo': 'Southern Europe',
    'Yugoslavia': 'Southern Europe', 'Serbia and Montenegro': 'Southern Europe', 'Montenegro.1': 'Southern Europe',

    'Czechia': 'Eastern Europe', 'Hungary': 'Eastern Europe', 'Poland': 'Eastern Europe', 'Slovakia': 'Eastern Europe',
    'Bulgaria': 'Eastern Europe', 'Romania': 'Eastern Europe', 'Belarus': 'Eastern Europe', 'Ukraine': 'Eastern Europe',
    'Russian Federation': 'Eastern Europe', 'Moldova, Republic of': 'Eastern Europe',

    # 亚洲子区域
    'China': 'Eastern Asia', 'Japan': 'Eastern Asia', 'Korea, Republic of': 'Eastern Asia', 'Taiwan': 'Eastern Asia',
    'Hong Kong': 'Eastern Asia', 'Macao': 'Eastern Asia', 'Mongolia': 'Eastern Asia', 'Korea, Democratic People’s Republic of': 'Eastern Asia',

    'Indonesia': 'South-Eastern Asia', 'Philippines': 'South-Eastern Asia', 'Thailand': 'South-Eastern Asia', 'Singapore': 'South-Eastern Asia',
    'Viet Nam': 'South-Eastern Asia', 'Malaysia': 'South-Eastern Asia', 'Cambodia': 'South-Eastern Asia', 'Brunei Darussalam': 'South-Eastern Asia',
    'Myanmar': 'South-Eastern Asia', 'Lao People’s Democratic Republic': 'South-Eastern Asia', 'Timor-Leste': 'South-Eastern Asia', 'East Timor': 'South-Eastern Asia',

    'India': 'Southern Asia', 'Pakistan': 'Southern Asia', 'Sri Lanka': 'Southern Asia', 'Bangladesh': 'Southern Asia',
    'Afghanistan': 'Southern Asia', 'Bhutan': 'Southern Asia',
    'Nepal': 'Southern Asia',  # ✅ add

    'Kazakhstan': 'Central Asia', 'Kyrgyzstan': 'Central Asia', 'Tajikistan': 'Central Asia', 'Turkmenistan': 'Central Asia', 'Uzbekistan': 'Central Asia',

    'Türkiye': 'Western Asia', 'Israel': 'Western Asia', 'United Arab Emirates': 'Western Asia', 'Saudi Arabia': 'Western Asia',
    'Oman': 'Western Asia', 'Qatar': 'Western Asia', 'Kuwait': 'Western Asia', 'Bahrain': 'Western Asia', 'Iran, Islamic Republic of': 'Western Asia',
    'Jordan': 'Western Asia', 'Lebanon': 'Western Asia', 'Syrian Arab Republic': 'Western Asia', 'Iraq': 'Western Asia', 'Yemen': 'Western Asia',
    'Armenia': 'Western Asia', 'Azerbaijan': 'Western Asia', 'Georgia': 'Western Asia', 'Cyprus': 'Western Asia', 'Occupied Palestinian Territory': 'Western Asia',

    # 非洲子区域
    'Morocco': 'Northern Africa', 'Egypt': 'Northern Africa', 'Algeria': 'Northern Africa', 'Tunisia': 'Northern Africa',
    'Libya': 'Northern Africa', 'Sudan': 'Northern Africa', 'Ceuta': 'Northern Africa', 'Melilla': 'Northern Africa',

    'Nigeria': 'Western Africa', 'Ghana': 'Western Africa', 'Côte d’Ivoire': 'Western Africa', 'Liberia': 'Western Africa',
    'Sierra Leone': 'Western Africa', 'Gambia': 'Western Africa', 'Mali': 'Western Africa', 'Senegal': 'Western Africa',
    'Guinea': 'Western Africa', 'Benin': 'Western Africa', 'Togo': 'Western Africa', 'Niger': 'Western Africa', 'Mauritania': 'Western Africa',
    'Cabo Verde': 'Western Africa', 'Burkina Faso': 'Western Africa',
    'Guinea-Bissau': 'Western Africa',  # ✅ add

    'Ethiopia': 'Eastern Africa', 'Kenya': 'Eastern Africa', 'Tanzania, United Republic of': 'Eastern Africa', 'Uganda': 'Eastern Africa',
    'Rwanda': 'Eastern Africa', 'Burundi': 'Eastern Africa', 'Mozambique': 'Eastern Africa', 'Madagascar': 'Eastern Africa',
    'Mauritius': 'Eastern Africa', 'Seychelles': 'Eastern Africa', 'Somalia': 'Eastern Africa', 'Djibouti': 'Eastern Africa',
    'Eritrea': 'Eastern Africa', 'Zimbabwe': 'Eastern Africa', 'Zambia': 'Eastern Africa', 'Mayotte': 'Eastern Africa',
    'Malawi': 'Eastern Africa',  # ✅ add
    'Comoros': 'Eastern Africa',  # ✅ add

    'Cameroon': 'Middle Africa', 'Congo, Democratic Republic of': 'Middle Africa', 'Congo': 'Middle Africa', 'Angola': 'Middle Africa',
    'Central African Republic': 'Middle Africa', 'Chad': 'Middle Africa', 'Gabon': 'Middle Africa', 'Equatorial Guinea': 'Middle Africa',
    'Sao Tome and Principe': 'Middle Africa',

    'South Africa': 'Southern Africa', 'Namibia': 'Southern Africa', 'Botswana': 'Southern Africa', 'Lesotho': 'Southern Africa',
    'Eswatini': 'Southern Africa',  # ✅ add
    'South Sudan': 'Eastern Africa',  # ✅ add (UN 通常归 Eastern Africa)

    # 美洲子区域
    'United States': 'Northern America', 'Canada': 'Northern America', 'Greenland': 'Northern America', 'Bermuda': 'Northern America',
    'St Pierre and Miquelon': 'Northern America',

    'Jamaica': 'Caribbean', 'Cuba': 'Caribbean', 'Haiti': 'Caribbean', 'Dominican Republic': 'Caribbean',
    'Bahamas': 'Caribbean', 'Barbados': 'Caribbean', 'Trinidad and Tobago': 'Caribbean', 'Dominica': 'Caribbean',
    'Antigua and Barbuda': 'Caribbean', 'St Lucia': 'Caribbean', 'Grenada': 'Caribbean', 'Virgin Islands, United States': 'Caribbean',
    'Virgin Islands, British': 'Caribbean', 'Cayman Islands': 'Caribbean', 'Turks and Caicos Islands': 'Caribbean',
    'Montserrat': 'Caribbean', 'Saint Barthélemy': 'Caribbean', 'Sint Maarten': 'Caribbean', 'Curaçao': 'Caribbean',
    'Netherlands Antilles': 'Caribbean',
    'Aruba': 'Caribbean',  # ✅ add
    'Bonaire, Sint Eustatius and Saba': 'Caribbean',  # ✅ add
    'St Vincent and the Grenadines': 'Caribbean',  # ✅ add
    'St Kitts and Nevis': 'Caribbean',  # ✅ add

    'Mexico': 'Central America', 'Belize': 'Central America', 'Costa Rica': 'Central America', 'El Salvador': 'Central America',
    'Guatemala': 'Central America', 'Honduras': 'Central America', 'Nicaragua': 'Central America', 'Panama': 'Central America',

    'Argentina': 'South America', 'Brazil': 'South America', 'Venezuela, Bolivarian Republic of': 'South America',
    'Chile': 'South America', 'Uruguay': 'South America', 'Paraguay': 'South America', 'Peru': 'South America',
    'Colombia': 'South America', 'Ecuador': 'South America', 'Bolivia, Plurinational State of': 'South America',
    'Guyana': 'South America', 'Suriname': 'South America', 'Falkland Islands': 'South America',
    'South Georgia and South Sandwich Islands': 'South America',  # ✅ add (UN 常并入 South America)

    # 大洋洲子区域
    'Australia': 'Australia and New Zealand', 'New Zealand': 'Australia and New Zealand', 'New Zealand Oceania': 'Australia and New Zealand',
    'Christmas Island': 'Australia and New Zealand', 'Cocos Islands': 'Australia and New Zealand',

    'Papua New Guinea': 'Melanesia', 'New Caledonia': 'Melanesia', 'Solomon Islands': 'Melanesia',
    'Fiji': 'Melanesia',  # ✅ add
    'Vanuatu': 'Melanesia',  # ✅ add

    'Marshall Islands': 'Micronesia', 'Northern Mariana Islands': 'Micronesia', 'Nauru': 'Micronesia',
    'United States Minor Outlying Islands': 'Micronesia',
    'Kiribati': 'Micronesia',  # ✅ add
    'Guam': 'Micronesia',  # ✅ add

    'Tuvalu': 'Polynesia', 'Tonga': 'Polynesia', 'Samoa': 'Polynesia', 'Cook Islands': 'Polynesia', 'French Polynesia': 'Polynesia',
    'Pitcairn': 'Polynesia', 'Tokelau': 'Polynesia', 'American Samoa': 'Polynesia',
    'Wallis and Futuna': 'Polynesia',  # ✅ add

    # 其它 / 特殊
    'Saint Helena, Ascension and Tristan da Cunha': 'Western Africa',
    'British Indian Ocean Territory': 'Eastern Africa',  # ✅ add (UN 常归 Eastern Africa)
    'Holy See': 'Southern Europe',  # ✅ add（你之前 continent_map 放 Europe，这里细分到 Southern Europe）
    'French Southern Territories': 'Antarctica',  # ✅ add
    'Bouvet Island': 'Antarctica',  # ✅ add
    'Antarctica': 'Antarctica',  # ✅ add
    'High seas': 'Other',  # ✅ add
}


# 添加细分区域列，未匹配的填 'Unknown'
eurostat_tyre_vehicle['partner_sub_region'] = eurostat_tyre_vehicle['partner'].map(region_map).fillna('Unknown')

print(eurostat_tyre_vehicle['partner_sub_region'].value_counts())

partner_sub_region
Western Europe               250806
Eastern Europe               205381
Northern Europe              172693
Southern Europe              161012
Eastern Asia                 104494
Western Asia                  54670
South-Eastern Asia            46460
Northern America              34282
Southern Asia                 18591
South America                 12101
Southern Africa                9527
Northern Africa                9257
Central America                6754
Australia and New Zealand      3528
Western Africa                  863
Caribbean                       839
Eastern Africa                  657
Central Asia                    553
Middle Africa                   528
Melanesia                       163
Polynesia                        80
Micronesia                       24
Antarctica                       16
Other                             3
Name: count, dtype: int64

In [40]:
eurostat_tyre_vehicle[eurostat_tyre_vehicle['partner_sub_region']=='Unknown']['partner'].unique()

array([], dtype=object)

In [41]:
eurostat_tyre_vehicle_2017_2025 = eurostat_tyre_vehicle[eurostat_tyre_vehicle['date']>="2017-01-01"]
eurostat_tyre_vehicle_2017_2025

,date,HS Code,PRODUCT,Category,General_Category,country,partner,value,weight,Type,partner_continent,partner_sub_region
24157,2017-01-01,401110,"New pneumatic tyres, of rubber, of a kind used...",PCR,PCR,Austria,Belgium,182683.0,4682300.0,Tyre,Europe,Western Europe
24158,2017-01-01,401110,"New pneumatic tyres, of rubber, of a kind used...",PCR,PCR,Austria,China,38152.0,1242500.0,Tyre,Asia,Eastern Asia
24159,2017-01-01,401110,"New pneumatic tyres, of rubber, of a kind used...",PCR,PCR,Austria,Czechia,677725.0,7827700.0,Tyre,Europe,Eastern Europe
24160,2017-01-01,401110,"New pneumatic tyres, of rubber, of a kind used...",PCR,PCR,Austria,Denmark,2272.0,54000.0,Tyre,Europe,Northern Europe
24161,2017-01-01,401110,"New pneumatic tyres, of rubber, of a kind used...",PCR,PCR,Austria,Estonia,1350.0,28100.0,Tyre,Europe,Northern Europe
...,...,...,...,...,...,...,...,...,...,...,...,...
443649,2019-12-01,871640,"Trailers and semi-trailers, not designed for r...",NaN,TBR,United Kingdom,Türkiye,37311.0,8300.0,Vehicle,Asia,Western Asia
443650,2019-12-01,871640,"Trailers and semi-trailers, not designed for r...",NaN,TBR,United Kingdom,United States,563487.0,72099.0,Vehicle,North America,Northern America
443651,2019-12-01,870919,"Works trucks, self-propelled, not fitted with ...",NaN,Specialty,United Kingdom,China,22180.0,1718.0,Vehicle,Asia,Eastern Asia
443652,2019-12-01,870919,"Works trucks, self-propelled, not fitted with ...",NaN,Specialty,United Kingdom,Netherlands,366207.0,38195.0,Vehicle,Europe,Western Europe
443653,2019-12-01,870919,"Works trucks, self-propelled, not fitted with ...",NaN,Specialty,United Kingdom,United States,84061.0,3541.0,Vehicle,North America,Northern America

In [42]:
# eurostat_product_2019_2025.to_csv('raw_data/tire_product_PCR_TBR_SP_2017_2025.csv',index=False, encoding='utf-8')

In [43]:
# eurostat_product.to_csv('raw_data/tire_product_PCR_TBR_SP.csv', index=False, encoding='utf-8')

In [44]:
eurostat_tyre_vehicle_2017_2025['HS Code'].unique()

array([  401110,   401170,   401180, 40112010, 40112090,   870911,
           8703,     8702,     8704,     8705,     8701,   871639,
         871640,   870919,   871620,   871631])

In [45]:
eurostat_tyre_vehicle_2017_2025.to_csv('eurostat_tyre_vehicle.csv',index=False, encoding='utf-8')

In [46]:
# eurostat_tyre_vehicle_2019_2025[['HS Code','PRODUCT']].drop_duplicates()